### ISSUE TITLE
Support for pypy?

### ISSUE THREAD

**Issue by archonic** [mrkn/pycall.rb#75]
I've tried setting the path to a pypy binary, but it's getting the `PyCall::PythonNotFound` error. I've confirmed that I can run python scripts with that binary.

Is pypy support feasible with pycall?

**Comment by mrkn** [comment]
@archonic I think the answer is No, because pycall.rb depends on CPython's C API for embedding Python interpreter.

Unfortunately, I don't know the internal of PyPy, so the investigation of the feasibility is very hard for me.
If you want to use pycall.rb with PyPy, and if you can perform the investigation, your contribution is always welcome!

**Comment by archonic** [comment]
Now that I've read a bit more about PyPy, I don't think it would make sense to pursue this. I believe I would need to run a fork of PyPy to mimic the CPython C API, which isn't worth it for me. Thanks for your work on pycall!
